---
version: "3"

volumes:
  traefik_acme_data: {}

services:
  traefik:
    build:
      context: .
      dockerfile: ./dockerfiles/traefik/Dockerfile
    image: mlflow_production_traefik
    restart: always
    volumes:
      - traefik_acme_data:/etc/traefik/acme/
      - ./config/.htpasswd:/etc/traefik/.htpasswd:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
    ports:
      - "0.0.0.0:80:8080"
      - "0.0.0.0:443:8443"

  mlflow:
    build:
      context: .
      dockerfile: ./dockerfiles/mlflow/Dockerfile
    image: mlflow_production_server
    restart: always
    command: /start
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - MLFLOW_ARTIFACT_URI=${MLFLOW_ARTIFACT_URI}
      # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      # - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
