---
log:
  level: INFO

entryPoints:
  web:
    address: ":80"

#   web-secure:
#     address: ":443"

# certificatesResolvers:
#   letsencrypt:
#     # https://docs.traefik.io/master/https/acme/#lets-encrypt
#     acme:
#       email: ${EMAIL_ADDRESS}
#       storage: /etc/traefik/acme/acme.json
#       # https://docs.traefik.io/master/https/acme/#httpchallenge
#       httpChallenge:
#         entryPoint: web

http:
  routers:
    web-router:
      rule: "Host(`${DOMAIN_NAME}`)"
      entryPoints:
        - web
      middlewares:
        - authorisation
      #   - redirect
      service: ${SERVICE_NAME}

  #   web-secure-router:
  #     rule: "Host(`${DOMAIN_NAME}`)"
  #     entryPoints:
  #       - web-secure
  #     service: ${SERVICE_NAME}
  #     tls:
  #       # https://docs.traefik.io/master/routing/routers/#certresolver
  #       certResolver: letsencrypt

  middlewares:
    # redirect:
    #   # https://docs.traefik.io/master/middlewares/redirectscheme/
    #   redirectScheme:
    #     scheme: https
    #     permanent: true
    authorisation:
      basicAuth:
        usersFile: /etc/traefik/.htpasswd
        removeHeader: true
        realm: ${REALM}

  services:
    ${SERVICE_NAME}:
      loadBalancer:
        servers:
          - url: http://${SERVICE_NAME}:${SERVICE_PORT}

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
