---
all:
  children:
    servers:
      vars:
        ansible_user: ubuntu
        ansible_ssh_user: ubuntu
        ansible_python_interpreter: /usr/bin/python3
      children:
        mlflow:
          hosts:
            ml-tracking-skwire.com:
